---
- name: Check if the postgresql packages are installed
  yum:
    name: "{{ postgresql_packages }}"
    state: present

- name: Check if postgresql libraries are installed
  yum:
    name: "{{ postgresql_python_library }}"
    state: present
